---

################################ Téléchargement / Installation d'Orchestrator ###########################################

- name: Ajout de la clé de dépôt ProxySQL
  apt_key:
    url: "https://repo.proxysql.com/ProxySQL/repo_pub_key"
    state: present

- name: Installation de proxysql (Debian)
  become: yes
  apt:
    name: "{{ deb_nginx_php }}"
    state: latest
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )



- include: proxysql-conf.yml
