---
################################## Gestion des Log nginx ###########################################

- name: Création du répértoire de log nginx
  become: yes
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root

################################## Fichier de Configuration nginx ###########################################

- name: Activation du service nginx au démarrage
  become: yes
  service:
    name: nginx
    enabled: yes

##??
- name: Ajout du fichier VHOST de nginx
  become: yes
  template:
    src: templates/sitewordpress.conf.j2
    dest: /etc/nginx/sites-enabled/sitewordpress.conf
  notify: "Restart service Nginx"

- name: Ajout de conf php-fpm
  become: yes
  template:
    src: templates/php-fpm.conf.j2
    dest: /etc/nginx/conf.d/php-fpm.conf
  notify: "Restart service Nginx"

##Exemple modification des droits 
#- name: Modification des droits sur le fichier de configuration d'orchestrator
#  become: yes
#  file:
#    path: /etc/orchestrator.conf.json
#    mode: '0600'
#  notify: "Restart service Orchestrator"


################################## Telechargement Wordpress unzip et supression ##################################


- name: Telechargement WordPress
  become : yes
  get_url:               # Télécharger wordpress et le placer dans /var/www
    url: http://fr.wordpress.org/latest-fr_FR.tar.gz
    dest: /var/www/latest-fr_FR.tar.gz
    force_basic_auth: yes

- name: Unzip wordpress
  become : yes
  unarchive:             # décomprésser l'archive = création d'un dossier wordpres
    src: /var/www/latest-fr_FR.tar.gz
    dest: /var/www/
    remote_src: yes

- name: supprimer le tar gz
  become : yes
  file:                  # suprimmer l'archive
    path: /var/www/latest-fr_FR.tar.gz
    state: absent

# Modification droits sur le dossier, CORRECT?????????
- name: Modification des droits sur le dossier wordpress
  become: yes
  file:
    path: /var/www/wordpress
    mode: '0700'
    owner: www-data
    group: www-data


# 
##Exemple d'ajout de dossier dans la machine avec des tours
#- name: Ajout des scripts orchestrator (Debian)
  # become: yes
  # template:
  #   src: templates/{{ item }}.j2
  #   dest: /var/tmp/{{ item }}
  # loop: 
  #   - prefailover.py
  #   - postfailover.py
  #   - ifDownPsql.py
  #   - upOldMaster.py
  
# Exemple de modification des droits sur plusieurs fichiers ajoutés
# - name: Modification des droits sur les scripts orchestrator (Debian)
#   become: yes
#   file:
#     path: /var/tmp/{{ item }}
#     mode: '0600'
#   loop: 
#     - prefailover.py
#     - postfailover.py
#     - ifDownPsql.py
#     - upOldMaster.py
#   notify: "Restart service Orchestrator"


- name: Démarrage du service nginx
  become: yes
  service: 
    name: nginx
    state: restarted