---

################################ Téléchargement / Installation de NGINX ###########################################

- name: Installation de nginx et PHP (Debian)
  become: yes
  apt:
    name: "{{ deb_nginx_php }}"
    state: latest
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

# vérifier l'éxistance du bon fichier de conf
# - name: Vérification de l'existence du fichier orchestrator-sample.conf.json (Debian)
#   become: yes
#   stat: path="/usr/local/orchestrator/orchestrator-sample.conf.json"
#   register: orch_conf_stat

- include: nginx-conf.yml
