---
################################## Gestion des Log nginx ###########################################

- name: Création du répértoire de log nginx
  become: yes
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root

################################## Fichier de Configuration nginx ###########################################

- name: Activation du service nginx au démarrage
  become: yes
  service:
    name: nginx
    enabled: yes


- name: Ajout du fichier VHOST de nginx
  become: yes
  template:
    src: templates/notreSite.conf.j2
    dest: /etc/nginx/sites-enabled/notreSite.conf
  notify: "Restart service Nginx"

- name: Ajout de conf php-fpm
  become: yes
  template:
    src: templates/php-fpm.conf.j2
    dest: /etc/nginx/conf.d/php-fpm.conf
  notify: "Restart service Nginx"

- name: Suppression du fichier de site par défaut
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent


################################## Ajout de notre site ##################################

# Modification droits sur le dossier
- name: Modification des droits sur notreSite
  become: yes
  file:
    path: /var/www/notreSite
    mode: '0700'
    state: directory
    owner: www-data
    group: www-data

- name: Ajout de notre site internet
  become: yes
  template:
    src: templates/{{ item }}.j2
    dest: /var/www/notreSite/{{ item }}
    owner: www-data
  notify: "Restart service Nginx"
  loop:
    - index.php
    - head.php
    - config.php

############ Gestion et création des certificats en local ############
      
- name: Création du répértoire des certificats
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    
- name: création de la clef privée
  become: yes
  local_action: openssl_privatekey
  args:
     path: /home/ansible/ansible/roles/nginx/files/privatekey.key
     size: 2048
     mode: '0666'  

- name: création de la clef publique
  become: yes
  local_action: openssl_csr
  args:
     path: /home/ansible/ansible/roles/nginx/files/publickey.csr
     privatekey_path: /home/ansible/ansible/roles/nginx/files/privatekey.key

- name: création du certificat
  become: yes
  local_action: openssl_certificate
  args:
     provider: selfsigned
     path: /home/ansible/ansible/roles/nginx/files/certificat.crt
     privatekey_path: /home/ansible/ansible/roles/nginx/files/privatekey.key
     csr_path: /home/ansible/ansible/roles/nginx/files/publickey.csr

############ Ajout des certificats sur le server web ############

- name: Copie de la clef publique
  become: yes
  copy:
    src: /home/ansible/ansible/roles/nginx/files/certificat.crt
    dest: /etc/nginx/ssl/certificat.crt
    owner: www-data
    group: www-data
    mode: 0600

- name: Copie de la clef privee
  become: yes
  copy:
    src: /home/ansible/ansible/roles/nginx/files/privatekey.key    
    dest: /etc/nginx/ssl/certificat.key
    owner: www-data
    group: www-data
    mode: 0600

############ reboot de nginx pour le final ############

- name: Redémarrage du service nginx
  become: yes
  service: 
    name: nginx
    state: restarted
