---
################################## Gestion des Log nginx ###########################################

- name: Création du répértoire de log nginx
  become: yes
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root

################################## Fichier de Configuration nginx ###########################################

- name: Activation du service nginx au démarrage
  become: yes
  service:
    name: nginx
    enabled: yes

##??
- name: Ajout du fichier VHOST de nginx
  become: yes
  template:
    src: templates/notreSite.conf.j2
    dest: /etc/nginx/sites-enabled/notreSite.conf
  notify: "Restart service Nginx"

- name: Ajout de conf php-fpm
  become: yes
  template:
    src: templates/php-fpm.conf.j2
    dest: /etc/nginx/conf.d/php-fpm.conf
  notify: "Restart service Nginx"

##Exemple modification des droits 
#- name: Modification des droits sur le fichier de configuration d'orchestrator
#  become: yes
#  file:
#    path: /etc/orchestrator.conf.json
#    mode: '0600'
#  notify: "Restart service Orchestrator"


################################## Ajout de notre site ##################################

- name: Ajout de notre site internet
  become: yes
  template:
    src: templates/{{ item }}.j2
    dest: /var/www/notreSite/{{ item }}
  notify: "Restart service Nginx"
  while:
    - index.php
    - head.php
    - config.php


# Modification droits sur le dossier
- name: Modification des droits sur notreSite
  become: yes
  file:
    path: /var/www/notreSite
    mode: '0700'
    owner: www-data
    group: www-data


- name: création des certificats
  become: yes
  local_action: openssl_certificate
  args: 
    path: /etc/ssl/crt/notreSite.crt
    privatekey_path: /etc/ssl/private/notreSite.pem
    csr_path: /etc/ssl/csr/notreSite.csr
    provider: selfsigned

# Exemple d'ajout de dossier dans la machine avec des tours
  #- name: Ajout des scripts orchestrator (Debian)
    # become: yes
    # template:
    #   src: templates/{{ item }}.j2
    #   dest: /var/tmp/{{ item }}
    # loop: 
    #   - prefailover.py
    #   - postfailover.py
    #   - ifDownPsql.py
    #   - upOldMaster.py
  
# Exemple de modification des droits sur plusieurs fichiers ajoutés
  # - name: Modification des droits sur les scripts orchestrator (Debian)
  #   become: yes
  #   file:
  #     path: /var/tmp/{{ item }}
  #     mode: '0600'
  #   loop: 
  #     - prefailover.py
  #     - postfailover.py
  #     - ifDownPsql.py
  #     - upOldMaster.py
  #   notify: "Restart service Orchestrator"


- name: Redémarrage du service nginx
  become: yes
  service: 
    name: nginx
    state: restarted