---

Sury_key: "https://packages.sury.org/php/apt.gpg"

Sury_repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"

NtpClient_Packages:
  - ntp
  - ntpdate

Chrony_Package:
  - chrony

Packages_Debian:
  - telnet
  - vim
  - ca-certificates
  - make
  - htop
  - subversion
  - rsync
  - unzip
  - libzip-dev
  - cifs-utils
  - lsb-release
  - wget
  - smem
  - tar
  - curl
  - screen
  - openssl
  - supervisor
  - iotop
  - sysstat
  - net-tools
  - python-pip
  - bmon
  - zip
  - atop
  - pv
  - git

atop_default_interval: "60"