---

#################################### Avant installation ###########################################

- name: Installation des paquets avant Lynis (Debian 10)
  become: yes
  apt:
    name: "{{ lynis_Debian_preresquites }}"
    state: latest
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

######################### Téléchargement / Installation de Lynis ################################

- name: Import de la clé GPG pour le dépôt Lynis (Debian)
  become: yes
  apt_key:
    url: "{{ lynis.deb.key }}"
    state: present
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

- name: Ajout du dépot Lynis (Debian)
  become: yes
  apt_repository:
    repo: "deb {{ lynis.deb.repo }} stable main"
    state: present
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

- name: Téléchargement de Lynis (Debian)
  become: yes
  apt: 
    name: lynis
    state: latest
    update_cache: yes
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

################## Lancement de Lynis et ajout d'un Banner MOTD #######################

- name: Création du group lynis
  group:
    name: lynis
    state: present

- name: Ajout des administrateur au groupe lynis
  user:
    name: "{{ item }}"
    groups: "lynis"
    append: yes
  with_items: "{{ lynis_autorized_user }}"

- name: Lancement de Lynis
  become: yes
  shell: "/usr/sbin/lynis audit system > /var/log/lynis.log && chown lynis:lynis /var/log/lynis.log"
  register: test_lynis
  when: lynis_first_try == "On" or lynis_first_try == "on"

- name: Ajout d'un Cron Lynis
  become: yes
  cron:
    name: "Lynis verif. Secu"
    hour: "4"
    user: root
    job: "/usr/sbin/lynis audit system > /var/log/lynis.log && chown lynis:lynis /var/log/lynis.log"
    cron_file: "lynis"

- name: Suppression des lignes pré-éxistantes dans le profil root
  become: yes
  lineinfile:
    path: "/root/.profile"
    state: absent
    regexp: "{{ online }}"

- name: Suppression des lignes pré-éxistantes dans le profil des administrateur
  become: yes
  lineinfile:
    path: "/home/{{ item }}/.profile"
    state: absent
    regexp: "{{ online }}"
  with_items: "{{ lynis_autorized_user }}"


- name: Ajout des lignes d'informations Lynis dans le profil des root
  become: yes
  blockinfile:
    path: /root/.profile
    block: "{{ lookup('file', '.profile.j2') }}"

- name: Ajout des lignes d'informations Lynis dans le profil des administrateur
  become: yes
  blockinfile:
    path: /home/{{ item }}/.profile
    block: "{{ lookup('file', '.profile.j2') }}"
  register: lynis_user_test
  with_items: "{{ lynis_autorized_user }}"
  #changed_when: (lynis_user_test.rc == 0) or (lynis_user_test.rc == 257)