---

#################################### TODO à déplacer/ Supprimer ###########################################

- name: Installation des paquets avant Percona (Debian 10)
  become: yes
  apt:
    name: "{{ Percona_Debian_preresquites }}"
    state: latest
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

#################################### Téléchargement / Installation de Percona ###########################################

- name: Téléchargement du dépot Percona (Debian 10)
  become: yes
  get_url:
    url: "{{ Percona_deb_repo }}"
    dest: /tmp/percona-release_latest.{{ ansible_lsb.codename }}_all.deb
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

- name: Installation du dépôt Percona (Debian 10)
  become: yes
  apt:
    deb: "/tmp/percona-release_latest.{{ ansible_lsb.codename }}_all.deb"
    state: present
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

- name: Activation du dépôt Percona
  become: yes
  command: "percona-release setup -y {{ percona_repo_version }} && percona-release enable tools release"
  changed_when: true

- name: Installation de Percona (Debian 10)
  become: yes
  apt:
    name: "{{ Percona_Debian }}"
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

- name: Suppression du fichier de dépot Percona (Debian 10)
  become: yes
  file:
    path: "/tmp/percona-release_latest.{{ ansible_lsb.codename }}_all.deb"
    state: absent
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version == "10" )

- name: Création du répertoire de données SQL
  become: yes
  file:
    path: "{{ datadir }}"
    state: directory
    owner: "mysql"
    group: "mysql"
    mode: '0700'

- include: conf.yml